=== Accredifysg/open-certificate/schema/transcripts/2.2/schema.json
{
  "$id": "opencerts/v2.2",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "identityProofDns": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["DNS-TXT"]
        },
        "location": {
          "type": "string",
          "description": "Url of the website referencing to document store"
        }
      },
      "required": ["type", "location"]
    },
    "identityProofDid": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["DID"]
        },
        "key": {
          "type": "string",
          "description": "Public key associated"
        }
      },
      "required": ["type", "key"]
    },
    "identityProofDnsDid": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["DNS-DID"]
        },
        "key": {
          "type": "string",
          "description": "Public key associated"
        },
        "location": {
          "type": "string",
          "description": "Url of the website referencing to document store"
        }
      },
      "required": ["type", "key", "location"]
    },
    "identityProof": {
      "type": "object",
      "oneOf": [
        { "$ref": "#/definitions/identityProofDns" },
        { "$ref": "#/definitions/identityProofDnsDid" },
        { "$ref": "#/definitions/identityProofDid" }
      ]
    },
    "documentStore": {
      "allOf": [
        { "$ref": "#/definitions/issuer" },
        {
          "type": "object",
          "properties": {
            "documentStore": {
              "type": "string"
            }
          },
          "required": ["documentStore"]
        }
      ]
    },
    "certificateStore": {
      "allOf": [
        { "$ref": "#/definitions/issuer" },
        {
          "type": "object",
          "properties": {
            "certificateStore": {
              "type": "string"
            }
          },
          "required": ["certificateStore"]
        }
      ]
    },
    "issuer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "did": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "url"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "phone": {
          "type": "string"
        },
        "identityProof": { "$ref": "#/definitions/identityProof" }
      },
      "required": ["name"],
      "additionalProperties": true
    }
  },
  "properties": {
    "id": {
      "type": "string"
    },
    "$template": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Template name to be use by template renderer to determine the template to use"
        },
        "type": {
          "type": "string",
          "description": "Type of renderer template",
          "enum": ["EMBEDDED_RENDERER"]
        },
        "url": {
          "type": "string",
          "description": "URL of a decentralised renderer to render this document"
        }
      },
      "required": ["name", "type", "url"]
    },
    "description": {
      "type": "string"
    },
    "issuedOn": {
      "description": "The date that this certificate was issued by the issuer(s)",
      "type": "string",
      "format": "date-time"
    },
    "expiresOn": {
      "type": "string",
      "format": "date-time"
    },
    "admissionDate": {
      "type": "string",
      "format": "date-time"
    },
    "graduationDate": {
      "description": "The date that this student graduated from the course",
      "type": "string",
      "format": "date-time"
    },
    "attainmentDate": {
      "description": "The date that this qualification was awarded to the recipient",
      "type": "string",
      "format": "date-time"
    },
    "qualificationLevel": {
      "type": "array",
      "description": "This is an array of objects used to attach descriptors from frameworks such as Singapore's SSEC-EQA or the internationally recognised ISCED. Multiple instances are allowed to indicate either equivalents or to indicate a multi-level qualifications",
      "items": {
        "type": "object",
        "required": [
          "frameworkName",
          "frameworkVersion",
          "code",
          "description"
        ],
        "properties": {
          "frameworkName": {
            "type": "string",
            "examples": ["singapore/ssec-eqa", "international/isced"]
          },
          "frameworkVersion": {
            "type": "string",
            "examples": ["2015", "2011"]
          },
          "code": {
            "type": "string",
            "examples": ["51", "55"]
          },
          "description": {
            "type": "string",
            "examples": [
              "Polytechnic Diploma",
              "(Short-cycle tertiary education) Vocational"
            ]
          }
        }
      }
    },
    "fieldOfStudy": {
      "type": "array",
      "description": "This is an array of objects used to attach descriptors from frameworks such as Singapore's SSEC-FOS or the internationally recognised ISCED-F. Multiple instances are allowed to indicate either equivalents or to indicate a multi-field qualification such as double degrees",
      "items": {
        "type": "object",
        "required": [
          "frameworkName",
          "frameworkVersion",
          "code",
          "description"
        ],
        "properties": {
          "frameworkName": {
            "type": "string",
            "description": "Prepend the actual framework name with the scope of the framework",
            "examples": ["singapore/ssec-fos", "international/isced-f"]
          },
          "frameworkVersion": {
            "type": "string",
            "examples": ["2015", "2013"]
          },
          "code": {
            "type": "string",
            "examples": ["0897"]
          },
          "description": {
            "type": "string",
            "examples": ["Biomedical Science"]
          }
        }
      }
    },
    "cumulativeScore": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "issuers": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "issuer",
        "oneOf": [
          {
            "$ref": "#/definitions/documentStore"
          },
          {
            "$ref": "#/definitions/certificateStore"
          },
          {
            "allOf": [
              { "$ref": "#/definitions/issuer" },
              {
                "not": {
                  "anyOf": [
                    {
                      "required": ["certificateStore"]
                    },
                    {
                      "required": ["documentStore"]
                    }
                  ]
                }
              }
            ]
          }
        ],
        "additionalProperties": true
      },
      "minItems": 1
    },
    "recipient": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "did": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "nric": {
          "type": "string"
        },
        "fin": {
          "type": "string"
        },
        "studentId": {
          "type": "string"
        }
      },
      "required": ["name"],
      "additionalProperties": true
    },
    "transcript": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "score": {
            "type": ["number", "string"]
          },
          "grade": {
            "type": ["number", "string"]
          },
          "courseCredit": {
            "type": ["number", "string"]
          },
          "courseCode": {
            "type": "string"
          },
          "examinationDate": {
            "type": "string",
            "format": "date-time"
          },
          "url": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "languageMedium": {
            "description": "Language that the course was undertaken in",
            "type": "string"
          }
        },
        "required": ["name"]
      }
    },
    "additionalData": {
      "type": "object"
    },
    "skills": {
      "description": "Information about skills that the recipient learnt",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "frameworkUri": {
            "description": "URI where to find the details about the framework",
            "type": "string",
            "format": "uri",
            "examples": ["https://www.skillsfuture.sg/skills-framework"]
          },
          "frameworkName": {
            "description": "Framework name",
            "type": "string",
            "examples": ["SFw"]
          },
          "frameworkVersion": {
            "description": "Framework version",
            "type": "string",
            "examples": ["1.0"]
          },
          "sector": {
            "description": "The industry/sector for which this framework is meant for",
            "type": "string",
            "examples": ["Air Transport"]
          },
          "category": {
            "description": "Skills and competency category. (Technical Skills Competency (TSC) or Critical Core Skills (CCS)",
            "type": "string",
            "examples": ["Aircraft Operations"]
          },
          "competencyCode": {
            "description": "Skills and competency code from Skills Framework",
            "type": "string",
            "examples": ["ATP-ACO-4001-1.1"]
          },
          "competencyDescription": {
            "description": "Detailed description of the skill or competency",
            "type": "string",
            "examples": [
              "Monitor aircraft systems, performance and external environments as well as comply with Air Traffic Control (ATC) instructions and en route navigation requirements to ensure safe and optimal flight conditions"
            ]
          },
          "competencyLevel": {
            "description": "Level of competency / skills: TSC Pro Level (numeric from 1 onward), GSC Pro Level (Critical Core Skills - basic, intermediate, advanced)",
            "type": "string",
            "examples": ["Level 4"]
          },
          "competencyLevelDescription": {
            "description": "Narrative information for this competency level",
            "type": "string",
            "examples": [
              "Analyse aircraft performance through close monitoring of flight decks to ensure optimal flight conditions during cruise"
            ]
          }
        },
        "required": ["frameworkUri", "frameworkName", "frameworkVersion"]
      }
    },
    "network": {
      "type": "object",
      "properties": {
        "chain": {
          "type": "string",
          "description": "Which blockchain being used"
        },
        "chainId": {
          "type": "string",
          "description": "Chain ID of the network used"
        }
      },
      "required": ["chain", "chainId"],
      "additionalProperties": true
    }
  },
  "required": ["id", "name", "issuedOn", "issuers", "recipient"],
  "additionalProperties": false
}

=== Accredifysg/open-certificate/schema/transcripts/2.2/example.json
{
  "id": "SERIAL-2018-08-01-112",
  "$template": {
    "name": "CUSTOM_TEMPLATE",
    "type": "EMBEDDED_RENDERER",
    "url": "https://demo-renderer.opencerts.io"
  },
  "description": "This masters is awarded to developers who can blockchain",
  "issuedOn": "2018-08-01T00:00:00+08:00",
  "expiresOn": "2118-08-01T00:00:00+08:00",
  "name": "Master of Blockchain",
  "admissionDate": "2017-07-01T00:00:00+08:00",
  "graduationDate": "2018-08-01T00:00:00+08:00",
  "attainmentDate": "2018-07-25T00:00:00+08:00",
  "issuers": [
    {
      "name": "Blockchain Academy",
      "did": "DID:SG-UEN:U18274928E",
      "url": "https://blockchainacademy.com",
      "email": "registrar@blockchainacademy.com",
      "documentStore": "0xd9580260be45c3c0c2fb259a82f219b513054012",
      "identityProof": {
        "type": "DNS-TXT",
        "location": "example.com"
      },
      "additionalProp": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    {
      "name": "School of Crypto-economics",
      "url": "https://ceschool.sg",
      "documentStore": "0xA33ddAEE02369D18A21E29dD2E7A12d65eE671d2",
      "identityProof": {
        "type": "DNS-TXT",
        "location": "example.com"
      }
    }
  ],
  "recipient": {
    "name": "Mr Blockchain",
    "did": "DID:SG-NRIC:S99999999A",
    "email": "mr-blockchain@gmail.com",
    "phone": "+65 88888888",
    "additionalProp": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nric": "S0000001Z",
    "fin": "F0000001Z",
    "studentId": "1232"
  },
  "qualificationLevel": [
    {
      "frameworkName": "singapore/ssec-eqa",
      "frameworkVersion": "2015",
      "code": "51",
      "description": "Polytechnic Diploma"
    },
    {
      "frameworkName": "international/isced",
      "frameworkVersion": "2011",
      "code": "55",
      "description": "(Short-cycle tertiary education) Vocational"
    }
  ],
  "fieldOfStudy": [
    {
      "frameworkName": "singapore/ssec-fos",
      "frameworkVersion": "2015",
      "code": "0897",
      "description": "Biomedical Science"
    }
  ],
  "transcript": [
    {
      "name": "Bitcoin",
      "grade": "A+",
      "courseCredit": 3,
      "courseCode": "BTC-01",
      "examinationDate": "2018-08-01T00:00:00+08:00",
      "url": "https://blockchainacademy.com/subject/BTC-01",
      "description": "Everything and more about bitcoin!"
    },
    {
      "name": "Ethereum",
      "grade": "A+",
      "courseCredit": "3.5",
      "courseCode": "ETH-01",
      "examinationDate": "2018-08-01T00:00:00+08:00",
      "url": "https://blockchainacademy.com/subject/ETH-01",
      "description": "Everything and more about ethereum!"
    }
  ],
  "cumulativeScore": 3.9935,
  "additionalData": {
    "coCurricularActivities": [
      {
        "name": "Crypto-investment Club",
        "position": "Club President",
        "startDate": "2017-08-01T00:00:00+08:00",
        "endDate": "2018-08-01T00:00:00+08:00",
        "remarks": "Top trader (2018)"
      }
    ],
    "npfa": "silver",
    "images": {
      "signature1": {
        "name": "Mr Important",
        "designation": "President",
        "signature": "<-- Base64 Image -->"
      },
      "signature2": {
        "name": "Mr Not-So-Important",
        "designation": "Chairman, Blockchain Faculty",
        "signature": "<-- Base64 Image -->"
      }
    }
  },
  "skills": [
    {
      "frameworkUri": "https://www.skillsfuture.sg/skills-framework",
      "frameworkVersion": "1.0",
      "frameworkName": "SFw",
      "sector": "Air Transport",
      "category": "Aircraft Operations",
      "competencyCode": "ATP-ACO-4001-1.1",
      "competencyDescription": "Monitor aircraft systems, performance and external environments as well as comply with Air Traffic Control (ATC) instructions and en route navigation requirements to ensure safe and optimal flight conditions",
      "competencyLevel": "Level 4",
      "competencyLevelDescription": "Analyse aircraft performance through close monitoring of flight decks to ensure optimal flight conditions during cruise"
    }
  ],
  "network": {
    "chain": "ETHEREUM",
    "chainId": "1"
  }
}
